### ISSUE TITLE
[CLOSED] Create module io.py to load data from csv into instance of spectrum class

### ISSUE THREAD

**Issue by ruffinevans** [ruffinevans/sivtempfit#9]
<a href="https://github.com/ruffinevans"><img src="https://avatars.githubusercontent.com/u/7091851?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ruffinevans](https://github.com/ruffinevans)**
_Thursday Apr 14, 2016 at 03:31 GMT_
_Originally opened as https://github.com/p201-sp2016/sivtempfit/issues/9_

----

**Comment by ruffinevans** [comment]
<a href="https://github.com/ruffinevans"><img src="https://avatars.githubusercontent.com/u/7091851?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ruffinevans](https://github.com/ruffinevans)**
_Thursday Apr 14, 2016 at 15:42 GMT_

----

@tdimiduk has offered to give me a code snippet to find the correct file path so that this works in any directory structure

**Comment by ruffinevans** [comment]
<a href="https://github.com/ruffinevans"><img src="https://avatars.githubusercontent.com/u/7091851?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ruffinevans](https://github.com/ruffinevans)**
_Tuesday Apr 19, 2016 at 01:38 GMT_

----

Loads JSON instead; this is the format I will use for the package. CSV does not support metadata, so it makes more sense to load that in using dataframes.

**Comment by tdimiduk** [comment]
Here is the code to do file lookups if you still need it:

https://github.com/p201-sp2016/package-example/blob/master/package_example/data_io.py#L6
